training:
  epochs: 30
  batch_size: 4
  num_workers: 2
  save_every_epoch: 1

generation:
  image_size: 64
  input_channels: 3
  output_channels: 3
  context_length: 4
  actions_count: 5

edm:
  # Noise schedule for training (log-normal)
  p_mean: -0.4
  p_std: 1.2

  # Data scaling
  sigma_data: 0.5

  # Karras schedule and sampler settings
  sigma_min: 0.002
  sigma_max: 5.0
  rho: 7
  order: 1            # 1: Euler, 2: Heun
  s_churn: 0.0
  s_tmin: 0.0
  s_tmax: .inf
  s_noise: 1.0

  # Stability tweaks
  sigma_offset_noise: 0.0
  quantize_output: true

  unet:
    __type__: models.gen.blocks.UNetConfig
    steps: [2, 2, 2, 2]
    channels: [64, 64, 64, 64]
    cond_channels: 256
    attn_step_indexes: [false, false, true, true]

ddpm:
  T: 1000
  unet:
    __type__: models.gen.blocks.UNetConfig
    steps: [2, 2, 2, 2]
    channels: [64, 64, 64, 64]
    cond_channels: 256
    attn_step_indexes: [false, false, true, true]
